### ISSUE TITLE
Yamaha P125 hookup

### ISSUE THREAD

**Issue by aconrath88** [leafo/sightreading.training#114]
I have a Yamaha P125 and iPad  ( newest gen ) using chrome, can I hook up to sight reading to automatically see my keyboard inputs to your app and index to next note.

I have connected my iPad into the Yamaha P125 through its USB port.

**Comment by mcbeanw01** [comment]
This is my issue too - did you fix it?

**Comment by leafo** [comment]
Not sure what is being reported here. In order to use the MIDI functionality you must have a MIDI device connected via USB on your computer, and you must be using a browser that supports MIDI connectivity. At the moment, Chrome and any derived browsers will work by default. Firefox can work if you enable the setting.

**Comment by mcbeanw01** [comment]
Hi and thx

I'm connecting via Type C to USB B cable.  It recognises it automatically,
and allows me to output to the piano, but won't recognise the input even
though it's selected....
